- name: enable i2c in /boot/config.txt
  shell: sed -i s'/\#dtparam\=i2c_arm\=on/dtparam\=i2c_arm\=on/g' /boot/config.txt
  when: inventory_hostname in groups["weather_station"]

- name: add pi to i2c group 
  user:
    name: pi 
    groups: i2c
  when: inventory_hostname in groups["weather-station"]

- name: reboot raspberry
  reboot:
    reboot_timeout: 300 #s
  when: inventory_hostname in groups["weather_station"]